version: '3.8'
services:
  app:
    build: .
    command: npm start --prefix ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/dapp/app/src:rw
      - /dapp/node_modules
      - /dapp/app/node_modules